window.KAMUS_VERBS = [
["memprogram","بَرْمَجَةٌ","barmajah","يُبَرْمِجُ","yubarmiju","بَرْمَجَ","barmaja"],
["menulis","كِتَابَةٌ","kitābah","يَكْتُبُ","yaktubu","كَتَبَ","kataba"],
["membaca","قِرَاءَةٌ","qirā'ah","يَقْرَأُ","yaqra'u","قَرَأَ","qara'a"],
["membuka","فَتْحٌ","fath","يَفْتَحُ","yaftahu","فَتَحَ","fataha"],
["menutup","إِغْلَاقٌ","ighlāq","يُغْلِقُ","yughliqu","أَغْلَقَ","aghlaqa"],
["menyimpan","حِفْظٌ","hifzh","يَحْفَظُ","yahfazhu","حَفِظَ","hafizha"],
["menghapus","حَذْفٌ","hadzf","يَحْذِفُ","yahdzifu","حَذَفَ","hadzafa"],
["menyalin","نَسْخٌ","naskh","يَنْسَخُ","yansakhu","نَسَخَ","nasakha"],
["menempelkan","إِلْصَاقٌ","ilshāq","يُلْصِقُ","yulshiqu","أَلْصَقَ","alshaqa"],
["menjalankan","تَشْغِيلٌ","tasyghīl","يُشَغِّلُ","yusyaghghilu","شَغَّلَ","syaghghala"],
["mendesain","تَصْمِيمٌ","tashmīm","يُصَمِّمُ","yushammimu","صَمَّمَ","shammama"],
["membuat","إِنْشَاءٌ","insyā'","يُنْشِئُ","yunsyi'u","أَنْشَأَ","ansya'a"],
["mengembangkan","تَطْوِيرٌ","tathwīr","يُطَوِّرُ","yuthawwiru","طَوَّرَ","thawwara"],
["mengeksekusi","تَنْفِيذٌ","tanfīdz","يُنَفِّذُ","yunaffidzu","نَفَّذَ","naffadza"],
["menguji","اِخْتِبَارٌ","ikhtibār","يَخْتَبِرُ","yakhtabiru","اِخْتَبَرَ","ikhtabara"],
["mengoreksi","تَصْحِيحٌ","tashhīh","يُصَحِّحُ","yushahhihu","صَحَّحَ","shahhaha"],
["memperbaiki","إِصْلَاحٌ","ishlāh","يُصْلِحُ","yushlihu","أَصْلَحَ","ashlaha"],
["menganalisis","تَحْلِيلٌ","tahlīl","يُحَلِّلُ","yuhallilu","حَلَّلَ","hallala"],
["memecahkan","حَلٌّ","hall","يَحُلُّ","yahullu","حَلَّ","halla"],
["mengubah","تَعْدِيلٌ","ta'dīl","يُعَدِّلُ","yu'addilu","عَدَّلَ","'addala"],
["menambahkan","إِضَافَةٌ","idhāfah","يُضِيفُ","yudhīfu","أَضَافَ","adhāfa"],
["menginstal","تَثْبِيتٌ","tatsbīt","يُثَبِّتُ","yutsabbitu","ثَبَّتَ","tsabbata"],
["memperbarui","تَحْدِيثٌ","tahdīts","يُحَدِّثُ","yuhadditsu","حَدَّثَ","haddatsa"],
["mengunduh","تَنْزِيلٌ","tanzīl","يُنَزِّلُ","yunazzilu","نَزَّلَ","nazzala"],
["mengunggah","رَفْعٌ","raf'","يَرْفَعُ","yarfa'u","رَفَعَ","rafa'a"],
["memasukkan","إِدْخَالٌ","idkhāl","يُدْخِلُ","yudkhilu","أَدْخَلَ","adkhala"],
["masuk","دُخُولٌ","dukhūl","يَدْخُلُ","yadkhulu","دَخَلَ","dakhala"],
["keluar","خُرُوجٌ","khurūj","يَخْرُجُ","yakhruju","خَرَجَ","kharaja"],
["terhubung","اِتِّصَالٌ","ittishāl","يَتَّصِلُ","yattashilu","اِتَّصَلَ","ittashala"],
["mengirim","إِرْسَالٌ","irsāl","يُرْسِلُ","yursilu","أَرْسَلَ","arsala"],
["menerima","اِسْتِقْبَالٌ","istiqbāl","يَسْتَقْبِلُ","yastaqbilu","اِسْتَقْبَلَ","istaqbala"],
["menyimpan data","تَخْزِينٌ","takhzīn","يُخَزِّنُ","yukhazzinu","خَزَّنَ","khazzana"],
["menggunakan","اِسْتِخْدَامٌ","istikhdām","يَسْتَخْدِمُ","yastakhdimu","اِسْتَخْدَمَ","istakhdama"],
["mencari","بَحْثٌ","bahts","يَبْحَثُ","yabhatsu","بَحَثَ","bahatsa"],
["mencetak","طِبَاعَةٌ","thibā'ah","يَطْبَعُ","yathba'u","طَبَعَ","thaba'a"],
["mengenkripsi","تَشْفِيرٌ","tasyfīr","يُشَفِّرُ","yusyaffiru","شَفَّرَ","syaffara"],
["melindungi","حِمَايَةٌ","himāyah","يَحْمِي","yahmī","حَمَى","hamā"],
["meretas","اِخْتِرَاقٌ","ikhtirāq","يَخْتَرِقُ","yakhtariqu","اِخْتَرَقَ","ikhtaraqa"],
["menggabungkan","دَمْجٌ","damj","يَدْمِجُ","yadmiju","دَمَجَ","damaja"],
["menerbitkan (deploy)","نَشْرٌ","nasyr","يَنْشُرُ","yansyuru","نَشَرَ","nasyara"],
["menampilkan","عَرْضٌ","'ardh","يَعْرِضُ","ya'ridhu","عَرَضَ","'aradha"],
["mencoba","تَجْرِبَةٌ","tajribah","يُجَرِّبُ","yujarribu","جَرَّبَ","jarraba"],
["belajar","تَعَلُّمٌ","ta'allum","يَتَعَلَّمُ","yata'allamu","تَعَلَّمَ","ta'allama"],
["mempelajari","دِرَاسَةٌ","dirāsah","يَدْرُسُ","yadrusu","دَرَسَ","darasa"],
["menjelaskan","شَرْحٌ","syarh","يَشْرَحُ","yasyrahu","شَرَحَ","syaraha"],
["bertanya","سُؤَالٌ","su'āl","يَسْأَلُ","yas'alu","سَأَلَ","sa'ala"],
["menjawab","إِجَابَةٌ","ijābah","يُجِيبُ","yujību","أَجَابَ","ajāba"],
["mendiskusikan","مُنَاقَشَةٌ","munāqasyah","يُنَاقِشُ","yunāqisyu","نَاقَشَ","nāqasya"],
["bekerja sama","تَعَاوُنٌ","ta'āwun","يَتَعَاوَنُ","yata'āwanu","تَعَاوَنَ","ta'āwana"],
["memulai","بَدْءٌ","bad'","يَبْدَأُ","yabda'u","بَدَأَ","bada'a"]
].map(v=>({id:v[0],mashdar:v[1],mashdarT:v[2],mudhari:v[3],mudhariT:v[4],madi:v[5],madiT:v[6]}));

window.KAMUS_PHRASES = [
["Belajar di kelas","صَبَاحُ الْخَيْرِ يَا أُسْتَاذُ.","shabāhu al-khairi yā ustādz.","Selamat pagi, Pak Guru."],
["Belajar di kelas","هَلْ يُمْكِنُنِي الدُّخُولُ؟","hal yumkinunī ad-dukhūl?","Bolehkah saya masuk?"],
["Belajar di kelas","اِفْتَحُوا الْكُتُبَ.","iftahū al-kutub.","Bukalah buku-buku."],
["Belajar di kelas","اُكْتُبْ هَذَا فِي الدَّفْتَرِ.","uktub hādzā fī ad-daftar.","Tulis ini di buku tulis."],
["Belajar di kelas","أَنَا آسِفٌ، تَأَخَّرْتُ.","anā āsifun, ta'akhkhartu.","Maaf, saya terlambat."],
["Belajar di kelas","شُكْرًا يَا أُسْتَاذُ.","syukran yā ustādz.","Terima kasih, Pak Guru."],
["Bertanya kepada guru","مِنْ فَضْلِكَ، لَدَيَّ سُؤَالٌ.","min fadhlika, ladayya su'āl.","Permisi, saya punya pertanyaan."],
["Bertanya kepada guru","هَلْ يُمْكِنُكَ أَنْ تَشْرَحَ مَرَّةً أُخْرَى؟","hal yumkinuka an tasyraha marratan ukhrā?","Bisakah Bapak menjelaskan sekali lagi?"],
["Bertanya kepada guru","لَمْ أَفْهَمْ.","lam afham.","Saya tidak paham."],
["Bertanya kepada guru","مَا مَعْنَى هَذِهِ الْكَلِمَةِ؟","mā ma'nā hādzihi al-kalimah?","Apa arti kata ini?"],
["Bertanya kepada guru","كَيْفَ أَكْتُبُ هَذَا الْأَمْرَ؟","kaifa aktubu hādzā al-amr?","Bagaimana saya menulis perintah ini?"],
["Bertanya kepada guru","هَلْ هَذَا الْجَوَابُ صَحِيحٌ؟","hal hādzā al-jawābu shahīh?","Apakah jawaban ini benar?"],
["Bertanya kepada guru","هَلْ عِنْدَكَ مِثَالٌ؟","hal 'indaka mitsāl?","Apakah Bapak punya contoh?"],
["Bertanya kepada guru","مَتَى مَوْعِدُ التَّسْلِيمِ؟","matā mau'idu at-taslīm?","Kapan batas pengumpulan?"],
["Praktik di lab komputer","شَغِّلِ الْحَاسُوبَ.","syaghghili al-hāsūb.","Nyalakan komputer."],
["Praktik di lab komputer","سَجِّلِ الدُّخُولَ بِحِسَابِكَ.","sajjili ad-dukhūla bihisābik.","Login dengan akunmu."],
["Praktik di lab komputer","اِفْتَحِ الْمُتَصَفِّحَ.","iftahi al-mutashaffih.","Buka peramban."],
["Praktik di lab komputer","اِحْفَظِ الْمِلَفَّ فِي الْمُجَلَّدِ.","ihfazhi al-milaffa fī al-mujallad.","Simpan berkas di folder."],
["Praktik di lab komputer","الْإِنْتَرْنِتُ بَطِيءٌ الْيَوْمَ.","al-intirnitu bathī'un al-yaum.","Internetnya lambat hari ini."],
["Praktik di lab komputer","أَغْلِقِ الْحَاسُوبَ بَعْدَ الِاسْتِخْدَامِ.","aghliqi al-hāsūba ba'da al-istikhdām.","Matikan komputer setelah dipakai."],
["Praktik di lab komputer","لَا تَنْسَ حِفْظَ عَمَلِكَ.","lā tansa hifzha 'amalik.","Jangan lupa menyimpan pekerjaanmu."],
["Praktik di lab komputer","هَلِ الْجِهَازُ يَعْمَلُ؟","hali al-jihāzu ya'mal?","Apakah perangkatnya berfungsi?"],
["Saat coding","أَنَا أَكْتُبُ الشِّيفْرَةَ الْآنَ.","anā aktubu asy-syīfrata al-ān.","Saya sedang menulis kode."],
["Saat coding","شَغِّلِ الْبَرْنَامَجَ.","syaghghili al-barnāmaj.","Jalankan program."],
["Saat coding","هَذَا الْمُتَغَيِّرُ يُخَزِّنُ الْعُمْرَ.","hādzā al-mutaghayyiru yukhazzinu al-'umr.","Variabel ini menyimpan umur."],
["Saat coding","أَنْشِئْ دَالَّةً جَدِيدَةً.","ansyi' dāllatan jadīdah.","Buatlah fungsi baru."],
["Saat coding","اِسْتَخْدِمْ حَلْقَةً تَكْرَارِيَّةً.","istakhdim halqatan takrāriyyah.","Gunakan perulangan."],
["Saat coding","كُلُّ كَائِنٍ لَهُ خَصَائِصُ.","kullu kā'inin lahu khashā'ish.","Setiap objek punya properti."],
["Saat coding","اُكْتُبْ تَعْلِيقًا لِشَرْحِ الشِّيفْرَةِ.","uktub ta'līqan lisyarhi asy-syīfrah.","Tulis komentar untuk menjelaskan kode."],
["Saat coding","أَرْفَعُ الْمَشْرُوعَ إِلَى GitHub.","arfa'u al-masyrū'a ilā GitHub.","Saya mengunggah proyek ke GitHub."],
["Menjelaskan error","ظَهَرَ خَطَأٌ فِي الْبَرْنَامَجِ.","zhahara khatha'un fī al-barnāmaj.","Muncul error di program."],
["Menjelaskan error","أَيْنَ الْخَطَأُ؟","aina al-khatha'?","Di mana errornya?"],
["Menjelaskan error","اِقْرَأْ رِسَالَةَ الْخَطَأِ.","iqra' risālata al-khatha'.","Baca pesan error."],
["Menjelaskan error","فِي الْمَشْرُوعِ خَلَلٌ بَرْمَجِيٌّ.","fī al-masyrū'i khalalun barmajiyy.","Ada bug di proyek."],
["Menjelaskan error","سَأُصَحِّحُ الْخَطَأَ الْآنَ.","sa-ushahhihu al-khatha'a al-ān.","Saya akan memperbaiki error sekarang."],
["Menjelaskan error","الْبَرْنَامَجُ لَا يَعْمَلُ.","al-barnāmaju lā ya'mal.","Programnya tidak berjalan."],
["Menjelaskan error","جَرِّبْ مَرَّةً أُخْرَى.","jarrib marratan ukhrā.","Coba sekali lagi."],
["Menjelaskan error","تَمَّ حَلُّ الْمُشْكِلَةِ.","tamma hallu al-musykilah.","Masalah sudah terpecahkan."],
["Menjelaskan error","أَظُنُّ أَنَّ الْخَطَأَ فِي هَذَا السَّطْرِ.","azhunnu anna al-khatha'a fī hādzā as-sathr.","Saya kira errornya di baris ini."],
["Kerja kelompok","نَحْنُ نَعْمَلُ كَفَرِيقٍ.","nahnu na'malu kafarīq.","Kami bekerja sebagai tim."],
["Kerja kelompok","مَنِ الْمَسْؤُولُ عَنْ هَذِهِ الْمَهَمَّةِ؟","mani al-mas'ūlu 'an hādzihi al-mahammah?","Siapa yang bertanggung jawab atas tugas ini?"],
["Kerja kelompok","لِنُنَاقِشِ الْفِكْرَةَ.","linunāqisyi al-fikrah.","Mari kita diskusikan ide ini."],
["Kerja kelompok","أَنَا أَقْتَرِحُ هَذَا الْحَلَّ.","anā aqtarihu hādzā al-hall.","Saya mengusulkan solusi ini."],
["Kerja kelompok","هَلْ تُسَاعِدُنِي؟","hal tusā'idunī?","Maukah kamu membantu saya?"],
["Kerja kelompok","سَنَلْتَقِي غَدًا.","sanaltaqī ghadā.","Kita bertemu besok."],
["Presentasi proyek","السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللهِ وَبَرَكَاتُهُ.","as-salāmu 'alaikum wa rahmatullāhi wa barakātuh.","Salam sejahtera, rahmat, dan berkah Allah bagi Anda."],
["Presentasi proyek","سَأَعْرِضُ مَشْرُوعَنَا الْيَوْمَ.","sa-a'ridhu masyrū'anā al-yaum.","Hari ini saya akan mempresentasikan proyek kami."],
["Presentasi proyek","هَذَا التَّطْبِيقُ يُسَاعِدُ الْمُسْتَخْدِمِينَ.","hādzā at-tathbīqu yusā'idu al-mustakhdimīn.","Aplikasi ini membantu para pengguna."],
["Presentasi proyek","اِسْتَخْدَمْنَا لُغَةَ Python.","istakhdamnā lughata Python.","Kami memakai bahasa Python."],
["Presentasi proyek","هَذِهِ هِيَ وَاجِهَةُ التَّطْبِيقِ.","hādzihi hiya wājihatu at-tathbīq.","Inilah tampilan aplikasinya."],
["Presentasi proyek","هَلْ عِنْدَكُمْ أَسْئِلَةٌ؟","hal 'indakum as'ilah?","Apakah ada pertanyaan?"],
["Presentasi proyek","شُكْرًا عَلَى حُسْنِ اسْتِمَاعِكُمْ.","syukran 'alā husni istimā'ikum.","Terima kasih atas perhatian Anda."]
].map(p=>({section:p[0],ar:p[1],trans:p[2],id:p[3]}));

window.KAMUS_EXAMPLES = [
["PEMROGRAMAN","أُحِبُّ الْبَرْمَجَةَ كَثِيرًا.","uhibbu al-barmajata katsīrā.","Saya sangat suka pemrograman."],
["PROGRAMMER","أَخِي مُبَرْمِجٌ فِي شَرِكَةٍ.","akhī mubarmijun fī syarikah.","Saudara laki-lakiku programmer di sebuah perusahaan."],
["KODE","هَذِهِ الشِّيفْرَةُ وَاضِحَةٌ.","hādzihi asy-syīfratu wādhihah.","Kode ini jelas."],
["ALGORITMA","نَكْتُبُ خَوَارِزْمِيَّةً لِحَلِّ الْمُشْكِلَةِ.","naktubu khawārizmiyyatan lihalli al-musykilah.","Kami menulis algoritma untuk memecahkan masalah."],
["VARIABEL","هَذَا الْمُتَغَيِّرُ يَحْمِلُ قِيمَةً.","hādzā al-mutaghayyiru yahmilu qīmah.","Variabel ini menyimpan sebuah nilai."],
["FUNGSI","كَتَبْتُ دَالَّةً لِحِسَابِ الْمَجْمُوعِ.","katabtu dāllatan lihisābi al-majmū'.","Saya menulis fungsi untuk menghitung jumlah."],
["CLASS & OBJECT","كُلُّ كَائِنٍ يَنْتَمِي إِلَى فِئَةٍ.","kullu kā'inin yantamī ilā fi'ah.","Setiap objek termasuk dalam sebuah kelas."],
["DATABASE","نُخَزِّنُ الْبَيَانَاتِ فِي قَاعِدَةِ بَيَانَاتٍ.","nukhazzinu al-bayānāti fī qā'idati bayānāt.","Kami menyimpan data di basis data."],
["QUERY & SQL","كَتَبْتُ اسْتِعْلَامًا بِلُغَةِ SQL.","katabtu isti'lāman bilughati SQL.","Saya menulis kueri dengan bahasa SQL."],
["SERVER & CLIENT","الْخَادِمُ يَسْتَقْبِلُ طَلَبَ الْعَمِيلِ.","al-khādimu yastaqbilu thalaba al-'amīl.","Server menerima permintaan klien."],
["FRONTEND","الْوَاجِهَةُ الْأَمَامِيَّةُ تَعْرِضُ الصَّفْحَةَ لِلْمُسْتَخْدِمِ.","al-wājihatu al-amāmiyyatu ta'ridhu ash-shafhata lilmustakhdim.","Frontend menampilkan halaman kepada pengguna."],
["BACKEND","الْوَاجِهَةُ الْخَلْفِيَّةُ تُعَالِجُ الْبَيَانَاتِ.","al-wājihatu al-khalfiyyatu tu'āliju al-bayānāt.","Backend memproses data."],
["FRAMEWORK","نَسْتَخْدِمُ إِطَارَ عَمَلٍ لِبِنَاءِ الْمَوْقِعِ.","nastakhdimu ithāra 'amalin libinā'i al-mauqi'.","Kami memakai framework untuk membangun situs."],
["API","يَرْبِطُ API بَيْنَ التَّطْبِيقَيْنِ.","yarbithu API baina at-tathbīqain.","API menghubungkan dua aplikasi."],
["GIT","أَحْفَظُ التَّغْيِيرَاتِ بِاسْتِخْدَامِ Git.","ahfazhu at-taghyīrāti bi-istikhdāmi Git.","Saya menyimpan perubahan memakai Git."],
["HTML","نَبْنِي هَيْكَلَ الصَّفْحَةِ بِلُغَةِ HTML.","nabnī haikala ash-shafhati bilughati HTML.","Kami membangun struktur halaman dengan HTML."],
["CSS","نُنَسِّقُ الصَّفْحَةَ بِلُغَةِ CSS.","nunassiqu ash-shafhata bilughati CSS.","Kami menata tampilan halaman dengan CSS."],
["JAVASCRIPT","تَجْعَلُ JavaScript الصَّفْحَةَ تَفَاعُلِيَّةً.","taj'alu JavaScript ash-shafhata tafā'uliyyah.","JavaScript membuat halaman menjadi interaktif."],
["PYTHON","Python لُغَةٌ سَهْلَةٌ لِلْمُبْتَدِئِينَ.","Python lughatun sahlatun lilmubtadi'īn.","Python adalah bahasa yang mudah untuk pemula."],
["DEBUGGING","تَصْحِيحُ الْأَخْطَاءِ جُزْءٌ مِنْ عَمَلِ الْمُبَرْمِجِ.","tashhīhu al-akhthā'i juz'un min 'amali al-mubarmij.","Debugging adalah bagian dari pekerjaan programmer."],
["BUG","وَجَدْتُ خَلَلًا بَرْمَجِيًّا فِي الْمَوْقِعِ.","wajadtu khalalan barmajiyyan fī al-mauqi'.","Saya menemukan bug di situs."],
["TESTING","نُجْرِي اخْتِبَارَ الْبَرْنَامَجِ قَبْلَ النَّشْرِ.","nujrī ikhtibāra al-barnāmaji qabla an-nasyr.","Kami menguji program sebelum deployment."],
["DEPLOYMENT","نَشَرْنَا التَّطْبِيقَ عَلَى الْإِنْتَرْنِتِ.","nasyarnā at-tathbīqa 'alā al-intirnit.","Kami men-deploy aplikasi ke internet."],
["WEBSITE","أُصَمِّمُ مَوْقِعًا إِلِكْتْرُونِيًّا لِلْمَدْرَسَةِ.","ushammimu mauqi'an iliktrūniyyan lilmadrasah.","Saya mendesain situs web untuk sekolah."],
["BROWSER","أَفْتَحُ الْمَوْقِعَ فِي الْمُتَصَفِّحِ.","aftahu al-mauqi'a fī al-mutashaffih.","Saya membuka situs di peramban."],
["DOMAIN & HOSTING","نَحْتَاجُ إِلَى اسْمِ نِطَاقٍ وَاسْتِضَافَةٍ.","nahtāju ilā ismi nithāqin wa-istidhāfah.","Kami butuh nama domain dan hosting."],
["LOGIN","سَجَّلْتُ الدُّخُولَ بِاسْمِ الْمُسْتَخْدِمِ وَكَلِمَةِ الْمُرُورِ.","sajjaltu ad-dukhūla bi-ismi al-mustakhdimi wa kalimati al-murūr.","Saya login dengan nama pengguna dan kata sandi."],
["PASSWORD","كَلِمَةُ الْمُرُورِ الْقَوِيَّةُ تَحْمِي حِسَابَكَ.","kalimatu al-murūri al-qawiyyatu tahmī hisābak.","Kata sandi yang kuat melindungi akunmu."],
["ADMIN & USER","مُدِيرُ النِّظَامِ يُدِيرُ الْمُسْتَخْدِمِينَ.","mudīru an-nizhāmi yudīru al-mustakhdimīn.","Admin mengelola para pengguna."],
["NETWORK","الشَّبَكَةُ مُتَّصِلَةٌ بِالْإِنْتَرْنِتِ.","asy-syabakatu muttashilatun bil-intirnit.","Jaringan terhubung ke internet."],
["WI-FI","هَلْ يُوجَدُ Wi-Fi فِي الْمُخْتَبَرِ؟","hal yūjadu Wi-Fi fī al-mukhtabar?","Apakah ada Wi-Fi di laboratorium?"],
["IP ADDRESS","لِكُلِّ جِهَازٍ عُنْوَانُ IP.","likulli jihāzin 'unwānu IP.","Setiap perangkat punya alamat IP."],
["MALWARE","الْبَرْمَجِيَّةُ الْخَبِيثَةُ تُتْلِفُ الْمِلَفَّاتِ.","al-barmajiyyatu al-khabītsatu tutlifu al-milaffāt.","Malware merusak berkas."],
["ENCRYPTION","التَّشْفِيرُ يَحْمِي الْبَيَانَاتِ السِّرِّيَّةَ.","at-tasyfīru yahmī al-bayānāti as-sirriyyah.","Enkripsi melindungi data rahasia."],
["USER","الْمُسْتَخْدِمُ يَضْغَطُ عَلَى الزِّرِّ.","al-mustakhdimu yadhghathu 'alā az-zirr.","Pengguna menekan tombol."],
["APPLICATION","هَذَا التَّطْبِيقُ سَهْلُ الِاسْتِخْدَامِ.","hādzā at-tathbīqu sahlu al-istikhdām.","Aplikasi ini mudah digunakan."],
["RPL","أَدْرُسُ هَنْدَسَةَ الْبَرْمَجِيَّاتِ فِي الْمَدْرَسَةِ.","adrusu handasata al-barmajiyyāti fī al-madrasah.","Saya belajar rekayasa perangkat lunak di sekolah."]
].map(e=>({title:e[0],ar:e[1],trans:e[2],id:e[3]}));